### ISSUE TITLE
Implement permutative checking

### ISSUE THREAD

**Issue by frostdpr** [frostdpr/word-search-robot#2]
For each unfound word found in the word bank, substitute out low confidence predictions with visually similar letters and find if that matches a real word(needs onboard dictionary) or makes it more similar to a real word (using some sort of custom similarity metric). Alternatively sub out letters in unfound words until we find it in the puzzle

**Comment by nocholasrift** [comment]
- [x] Add dictionary on board

- [ ] Retrieve confidence level of words not found in initial pass

- [ ] Gather list of of possible words with confidence level from tesseract

- [x] Retry solve with new words

- [x] Add support for "smart spellcheck"

- [ ] Swap similar letters

**Comment by frostdpr** [comment]
Some spell check stuff that looks promising...
https://pypi.org/project/pyspellchecker/ 
or 
https://github.com/bakwc/JamSpell
